### ISSUE TITLE
Color picker does not work

### ISSUE THREAD

**Issue by Saltwaterhair** [schteppe/fb-node-issues#116]
Color picker does not work.

For future reference it would also be a good idea to move it into frame or fill up the screen on the phone for easier picking

**Comment by schteppe** [comment]
Will use this in the future, will notify when done: https://github.com/mjolnic/bootstrap-colorpicker

**Comment by schteppe** [comment]
Made it a little better in normal generator. Also disabled zooming on that page, to make it easier to edit. Check it out :)
